package main

const (
	xmlContent = `<?xml version="1.0" encoding="UTF-8"?>
  <?xml-stylesheet type="text/xsl" href="/file/stylesheets/inhistory.xsl"?>
  <c:inhistory xmlns:c="http://www.topcall.com/2006/store">
    <c:objectlist>
      <c:paglen>50</c:paglen>
      <c:selection>1433395206</c:selection>
      <c:ntotal>192</c:ntotal>
      <c:listoffset>0</c:listoffset>
      <c:nlisted>50</c:nlisted>
      <c:object>
        <c:common>
          <c:uuid>02c6f7b2-31f3-429e-8c45-40c4dbf722d3</c:uuid>
          <c:blocks>782</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:31:49.003</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_172325.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:31:44.905</TimeStart>
            <TimeEnd>2018-03-26T15:31:44.827</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_172325.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>6ece0dd3-ab5a-4563-8330-5a2302abc983</c:uuid>
          <c:blocks>728</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:30:44.549</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_172218.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:30:35.416</TimeStart>
            <TimeEnd>2018-03-26T15:30:35.322</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_172218.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>c6d2158a-11d3-4558-9f30-d6154da254ac</c:uuid>
          <c:blocks>729</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:29:39.806</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_172122.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:29:36.372</TimeStart>
            <TimeEnd>2018-03-26T15:29:36.309</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_172122.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>54143f7f-2f72-4b98-8b17-c8d670dcd26e</c:uuid>
          <c:blocks>658</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:28:45.389</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_172020.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:28:39.100</TimeStart>
            <TimeEnd>2018-03-26T15:28:39.006</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_172020.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>a2fc7064-7c3a-48d2-9f4a-2b6c64422a3b</c:uuid>
          <c:blocks>620</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:28:01.399</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_171929.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:27:49.362</TimeStart>
            <TimeEnd>2018-03-26T15:27:49.284</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_171929.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>d7b2a330-1125-4c4c-acb1-33eb16b39e77</c:uuid>
          <c:blocks>722</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:25:15.544</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_171647.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:25:05.636</TimeStart>
            <TimeEnd>2018-03-26T15:25:05.558</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_171647.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>647201d7-16e0-421a-8879-580981939428</c:uuid>
          <c:blocks>660</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:24:31.398</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_171604.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:24:20.313</TimeStart>
            <TimeEnd>2018-03-26T15:24:20.173</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_171604.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>7eb45271-cbbf-4c58-9cff-b3ca1bb0de7e</c:uuid>
          <c:blocks>618</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T15:23:43.633</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_171518.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T15:23:33.723</TimeStart>
            <TimeEnd>2018-03-26T15:23:33.645</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_171518.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>12b6a43c-2b97-4ba2-b1b2-64a01505bb12</c:uuid>
          <c:blocks>136</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T10:01:05.899</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_115238.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T10:00:55.415</TimeStart>
            <TimeEnd>2018-03-26T10:00:55.400</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_115238.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>e235a111-f948-4482-894f-4aedd65d250b</c:uuid>
          <c:blocks>118</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T10:00:13.696</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_115203.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T10:00:10.841</TimeStart>
            <TimeEnd>2018-03-26T10:00:10.810</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_115203.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>cc01657a-0cdc-45f1-8675-922a44a7569c</c:uuid>
          <c:blocks>152</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:59:52.071</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_115138.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:59:49.154</TimeStart>
            <TimeEnd>2018-03-26T09:59:49.123</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_115138.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>b0b89888-7d6e-4b23-b7f5-5c1c53b6a07b</c:uuid>
          <c:blocks>155</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:59:30.323</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_115103.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:59:21.977</TimeStart>
            <TimeEnd>2018-03-26T09:59:21.946</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_115103.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>4edee422-7b1f-4995-8503-f77337166a2b</c:uuid>
          <c:blocks>103</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:58:27.967</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_115008.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:58:25.220</TimeStart>
            <TimeEnd>2018-03-26T09:58:25.189</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_115008.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>d19244f7-1c68-4bbd-be33-7b8546202121</c:uuid>
          <c:blocks>196</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:58:06.563</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_114950.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:58:01.117</TimeStart>
            <TimeEnd>2018-03-26T09:58:01.070</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_114950.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>b68be8da-1dd8-4f94-aa16-5bbd6e8a0fee</c:uuid>
          <c:blocks>196</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:53:20.617</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_114500.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:53:11.534</TimeStart>
            <TimeEnd>2018-03-26T09:53:11.519</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_114500.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>a123ccd9-2d74-409e-a2a9-1d36b04ac76d</c:uuid>
          <c:blocks>240</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:52:38.515</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_114427.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:52:36.830</TimeStart>
            <TimeEnd>2018-03-26T09:52:36.799</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_114427.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>f0cfbd2f-6f9f-43f2-a22d-e46aef96c107</c:uuid>
          <c:blocks>237</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:52:26.810</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_114410.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:52:25.125</TimeStart>
            <TimeEnd>2018-03-26T09:52:25.109</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_114410.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>4cee4039-f004-4467-9282-e2167dcec0ef</c:uuid>
          <c:blocks>293</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:49:52.703</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_114127.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:49:42.641</TimeStart>
            <TimeEnd>2018-03-26T09:49:42.594</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_114127.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>7d574636-1e90-4c6f-a5d4-0a3cab3ba2b6</c:uuid>
          <c:blocks>298</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:49:10.586</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_114055.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:49:07.778</TimeStart>
            <TimeEnd>2018-03-26T09:49:07.747</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_114055.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>e83dfee3-cc5c-4c37-b78b-7b14de149c34</c:uuid>
          <c:blocks>248</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:48:38.495</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_114020.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:48:34.891</TimeStart>
            <TimeEnd>2018-03-26T09:48:34.876</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_114020.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>368c41c8-30db-4e58-875d-4f288676d8b2</c:uuid>
          <c:blocks>313</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:48:16.560</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_113953.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:48:12.004</TimeStart>
            <TimeEnd>2018-03-26T09:48:11.958</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_113953.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>41421784-662b-4b02-b603-ef1a70e83b02</c:uuid>
          <c:blocks>323</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:47:44.226</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_113922.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:47:37.830</TimeStart>
            <TimeEnd>2018-03-26T09:47:37.783</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_113922.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>d90f23f3-7754-4ee4-a0d8-ba3edacad672</c:uuid>
          <c:blocks>296</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T09:47:07.673</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_113849.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T09:47:02.891</TimeStart>
            <TimeEnd>2018-03-26T09:47:02.860</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_113849.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>c80e765b-8a6a-428c-aaf3-4e5f537e9d41</c:uuid>
          <c:blocks>317</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:09:42.420</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_100121.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:09:33.677</TimeStart>
            <TimeEnd>2018-03-26T08:09:33.630</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_100121.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>83a4edc8-dc97-4904-b5c0-8ae68eb880c7</c:uuid>
          <c:blocks>307</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:07:57.973</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095937.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:07:47.708</TimeStart>
            <TimeEnd>2018-03-26T08:07:47.661</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095937.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>ee115a19-0a30-4026-af3f-f28e39569466</c:uuid>
          <c:blocks>289</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:07:15.064</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095857.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:07:12.596</TimeStart>
            <TimeEnd>2018-03-26T08:07:12.524</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095857.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>a7b9b11f-ac7d-497f-972d-c3c26e85ccd0</c:uuid>
          <c:blocks>311</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:04:59.904</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095647.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:04:56.604</TimeStart>
            <TimeEnd>2018-03-26T08:04:56.462</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095647.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>507fcdf2-c320-447c-b010-bd9349b7a56d</c:uuid>
          <c:blocks>316</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:04:37.682</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095611.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:04:29.180</TimeStart>
            <TimeEnd>2018-03-26T08:04:29.118</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095611.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>e4f76ec9-7ba5-468d-b0bf-6519c8d0747c</c:uuid>
          <c:blocks>317</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:03:55.282</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095535.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:03:53.321</TimeStart>
            <TimeEnd>2018-03-26T08:03:53.289</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095535.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>8b159685-4317-48b8-bd0a-7ce62a4b3f96</c:uuid>
          <c:blocks>316</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:03:12.793</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095458.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:03:08.827</TimeStart>
            <TimeEnd>2018-03-26T08:03:08.796</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095458.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>c8d8e13a-03d4-47af-8abe-3b0d456a61c8</c:uuid>
          <c:blocks>301</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:02:30.145</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095413.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:02:26.295</TimeStart>
            <TimeEnd>2018-03-26T08:02:26.217</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095413.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>27ed3a08-24d1-414e-96a4-3355a8d3c91d</c:uuid>
          <c:blocks>316</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:01:47.586</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095328.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:01:36.289</TimeStart>
            <TimeEnd>2018-03-26T08:01:36.257</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095328.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>eebb81ca-752e-4927-b392-b88c43892afd</c:uuid>
          <c:blocks>312</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:01:05.077</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095248.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:01:01.809</TimeStart>
            <TimeEnd>2018-03-26T08:01:01.763</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095248.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>475a17cb-6105-4f10-a7a4-75a0a08f4c12</c:uuid>
          <c:blocks>305</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T08:00:21.336</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095205.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T08:00:14.181</TimeStart>
            <TimeEnd>2018-03-26T08:00:14.087</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095205.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>c0e0db70-509b-4306-8dd4-11c7abcf77cf</c:uuid>
          <c:blocks>306</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T07:59:28.384</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_095115.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T07:59:26.306</TimeStart>
            <TimeEnd>2018-03-26T07:59:26.274</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_095115.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>5c008a2f-e3cc-4af1-98dc-1d50ab4f9530</c:uuid>
          <c:blocks>308</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T07:55:51.725</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_094737.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T07:55:47.651</TimeStart>
            <TimeEnd>2018-03-26T07:55:47.604</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_094737.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>0a9b3aea-ae36-4ddf-af7a-d63f7192e305</c:uuid>
          <c:blocks>308</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T07:55:09.273</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_094652.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T07:55:00.867</TimeStart>
            <TimeEnd>2018-03-26T07:55:00.835</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_094652.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>dc350491-8a6c-40af-bf05-9bced3cfd434</c:uuid>
          <c:blocks>314</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T07:54:15.057</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_094545.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T07:54:00.259</TimeStart>
            <TimeEnd>2018-03-26T07:54:00.196</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_094545.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>5c297129-d384-4bcd-af21-6abc26d9fbf3</c:uuid>
          <c:blocks>314</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-26T07:53:28.077</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_26032018_094513.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-26T07:53:25.138</TimeStart>
            <TimeEnd>2018-03-26T07:53:25.106</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_26032018_094513.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>814bba3b-08d9-4644-bd8d-fb8f377e4d03</c:uuid>
          <c:blocks>311</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:31:23.831</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_102312.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:31:19.897</TimeStart>
            <TimeEnd>2018-03-23T09:31:19.851</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_102312.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>8c204d50-6ef3-4858-b52e-ed2f6f060e85</c:uuid>
          <c:blocks>307</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:30:51.252</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_102243.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:30:47.648</TimeStart>
            <TimeEnd>2018-03-23T09:30:47.601</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_102243.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>8a80be1f-de5e-4efd-b88e-ee1f8fc8fe2b</c:uuid>
          <c:blocks>313</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:30:19.227</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_102215.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:30:16.076</TimeStart>
            <TimeEnd>2018-03-23T09:30:16.029</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_102215.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>311badef-5568-42d2-948b-143acfba8cf3</c:uuid>
          <c:blocks>190</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:29:57.144</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_102139.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:29:47.470</TimeStart>
            <TimeEnd>2018-03-23T09:29:47.408</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_102139.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>7b679d9a-6c38-414c-beb4-f0d3743f8d0f</c:uuid>
          <c:blocks>310</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:29:15.232</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_102111.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:29:12.953</TimeStart>
            <TimeEnd>2018-03-23T09:29:12.890</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_102111.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>7ef187d8-7f7b-4a1f-9a99-1adc26bd183f</c:uuid>
          <c:blocks>311</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:28:52.883</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_102041.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:28:49.683</TimeStart>
            <TimeEnd>2018-03-23T09:28:49.637</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_102041.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>3c9705c0-4804-4acc-998b-8133fd1020d3</c:uuid>
          <c:blocks>298</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:28:10.386</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_102003.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:28:06.094</TimeStart>
            <TimeEnd>2018-03-23T09:28:06.032</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_102003.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>23f0cecf-04f6-4935-97fc-01554fa0c34f</c:uuid>
          <c:blocks>305</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:27:37.838</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_101932.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:27:33.200</TimeStart>
            <TimeEnd>2018-03-23T09:27:33.153</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_101932.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>a155ff80-da0e-4179-b4ed-3dd4868dbec0</c:uuid>
          <c:blocks>309</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:27:05.365</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_101856.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:27:00.899</TimeStart>
            <TimeEnd>2018-03-23T09:27:00.789</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_101856.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>0efe33eb-8e83-4b25-bfc0-b3210e1fee1e</c:uuid>
          <c:blocks>312</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:26:42.620</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_101825.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:26:30.665</TimeStart>
            <TimeEnd>2018-03-23T09:26:30.618</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_101825.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
      <c:object>
        <c:common>
          <c:uuid>48180d06-95ef-4c7c-b40f-40416ee1ce32</c:uuid>
          <c:blocks>309</c:blocks>
          <c:update>2</c:update>
        </c:common>
        <c:header>
          <general>
            <Act>0</Act>
            <Box>1</Box>
            <Type>3</Type>
            <deliver>
              <State>800</State>
              <TimeScheduled>2018-03-23T09:25:49.700</TimeScheduled>
              <Response>Message imported into Kofax Capture.</Response>
              <Tries>.</Tries>
            </deliver>
            <DisplayFrom>C:\import_folder\DOC_23032018_101745.tif</DisplayFrom>
            <DisplayRecipientList>folderimport@kcic-aef,</DisplayRecipientList>
            <DisplayTo></DisplayTo>
            <DisplaySubject></DisplaySubject>
            <OwnerReference></OwnerReference>
            <TimeStart>2018-03-23T09:25:45.800</TimeStart>
            <TimeEnd>2018-03-23T09:25:45.768</TimeEnd>
            <ContentErrorLevel>0</ContentErrorLevel>
            <ContentErrorList></ContentErrorList>
            <RootXml></RootXml>
          </general>
          <specific>
            <import>
              <Folder>C:\import_folder</Folder>
              <TriggerFileUsed>0</TriggerFileUsed>
              <FileList>
                <FilePath>C:\import_folder\DOC_23032018_101745.tif</FilePath>
              </FileList>
            </import>
          </specific>
        </c:header>
      </c:object>
    </c:objectlist>
  </c:inhistory>
`
)
