apiVersion: v1
kind: ReplicationController
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE_NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE_NAME}
        envFrom:
        - configMapRef:
            name: ${APP_NAME}-configmap
        ports:
        - containerPort: ${APP_PORT}
      imagePullSecrets:
      - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE_NAME}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: ${APP_PORT}
      targetPort: ${APP_PORT}
  selector:
    run: ${APP_NAME}